# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Netherlands eScience Center Github organizations
email: info@esciencecenter.nl
description: Overview of Github organizations of all NLeSC projects
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: esciencecenter
github_username: NLeSC

# Build settings
markdown: kramdown
permalink: pretty
collections:
- organizations
